
-- This script was generated by the ERD tool in pgAdmin 4 and viewed and checked by Luka
-- Better look at backups, this only first version with many mistakes

BEGIN;





-- |---------- adding tables ----------|

-- |--- account ---|
SAVEPOINT "account";

CREATE TABLE IF NOT EXISTS flavourhaven.account
(
    id_account SERIAL NOT NULL,
    user_name character varying(35) NOT NULL,
    birth_date time without time zone NOT NULL,
    "e-mail" character varying(60) NOT NULL,
    password character varying(60) NOT NULL,
    created_on timestamp without time zone NOT NULL,
    last_login timestamp without time zone,
    is_active boolean,
    role_id integer,
    last_pasword_reset timestamp without time zone,
    nickname character varying(35),
    profile_picture bytea,
    biography text,
    is_deleted boolean NOT NULL DEFAULT false,
    SERIAL PRIMARY KEY (id_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_saves_recipe
(
    id_account_saves_recipe SERIAL NOT NULL,
    account_id integer NOT NULL,
    saved_recipe_id integer NOT NULL,
    PRIMARY KEY (id_account_saves_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_rates_recipe
(
    id_account_rates_recipe SERIAL NOT NULL,
    account_id integer NOT NULL,
    rated_recipe_id integer NOT NULL,
    is_positive boolean NOT NULL,
    PRIMARY KEY (id_account_rates_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_rates_comment
(
    id_account_rates_comment SERIAL NOT NULL,
    account_id integer NOT NULL,
    rated_comment_id integer NOT NULL,
    is_positve boolean NOT NULL,
    PRIMARY KEY (id_account_rates_comment)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_subscibes_account
(
    id_account_subscibes_account SERIAL NOT NULL,
    account_id integer NOT NULL,
    subscibed_account_id integer NOT NULL,
    PRIMARY KEY (id_account_subscibes_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_blocks_account
(
    id_account_blocks_account SERIAL NOT NULL,
    account_id integer NOT NULL,
    blocked_account_id integer NOT NULL,
    PRIMARY KEY (id_account_blocks_account)
);



-- |--- recipe ---|
SAVEPOINT "recipe";

CREATE TABLE IF NOT EXISTS flavourhaven.recipe
(
    id_recipe SERIAL NOT NULL,
    title character varying(60) NOT NULL,
    thumbnail bytea NOT NULL,
    main_image bytea,
    cooking_video bytea,
    resting_time_in_min integer,
    preparation_time_in_min integer,
    cooking_time_in_min integer,
    serving_amount numeric(4, 2),
    creator_account_id integer NOT NULL,
    created_on time without time zone,
    cuisine_id integer NOT NULL,
    food_type_id integer NOT NULL,
    when_sesonality character varying(60),
    is_deleted boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_links_account
(
    id_recipe_links_account SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    links_account_id integer NOT NULL,
    description character varying(100),
    PRIMARY KEY (id_recipe_links_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_links_recipe
(
    id_recipe_links_recipe SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    links_recipe_id integer NOT NULL,
    description character varying(100),
    PRIMARY KEY (id_recipe_links_recipe)
);



-- |--- food ---|
SAVEPOINT "food";

CREATE TABLE IF NOT EXISTS flavourhaven.food_type
(
    id_food_type SERIAL NOT NULL,
    name integer NOT NULL,
    PRIMARY KEY (id_food_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.cuisine
(
    id_cuisine SERIAL NOT NULL,
    name integer NOT NULL,
    PRIMARY KEY (id_cuisine)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_food_type
(
    id_recipe_has_food_type SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    food_type_id integer NOT NULL,
    PRIMARY KEY (id_recipe_has_food_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_cuisine
(
    id_recipe_has_cuisine SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    cuisine_id integer NOT NULL,
    PRIMARY KEY (id_recipe_has_cuisine)
);



-- |--- mail ---|
SAVEPOINT "mail";

CREATE TABLE IF NOT EXISTS flavourhaven.mail
(
    id_mail SERIAL NOT NULL,
    account_id integer NOT NULL,
    text text,
    PRIMARY KEY (id_mail)
);



-- |--- link ---|
SAVEPOINT "link";

CREATE TABLE IF NOT EXISTS flavourhaven.link
(
    id_link SERIAL NOT NULL,
    link text NOT NULL,
    where_to character varying(45) NOT NULL,
    icon bytea,
    PRIMARY KEY (id_link)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_has_link
(
    id_account_has_link SERIAL NOT NULL,
    link_id integer NOT NULL,
    account_id integer NOT NULL,
    PRIMARY KEY (id_account_has_link)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_link
(
    id_recipe_has_link SERIAL NOT NULL,
    link_id integer NOT NULL,
    recipe_id integer NOT NULL,
    PRIMARY KEY (id_recipe_has_link)
);



-- |--- listing ---|
SAVEPOINT "listing";

CREATE TABLE IF NOT EXISTS flavourhaven.listing
(
    id_listing SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    title character varying(50),
    hirarchy integer NOT NULL,
    listing_type_id integer NOT NULL,
    PRIMARY KEY (id_listing)
);

CREATE TABLE IF NOT EXISTS flavourhaven.listing_type
(
    id_listing_type SERIAL NOT NULL,
    name character varying(15) NOT NULL,
    PRIMARY KEY (id_listing_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.ingredient
(
    id_ingredient SERIAL NOT NULL,
    listing_id integer NOT NULL,
    name character varying(100) NOT NULL,
    additional_information text NOT NULL,
    amount numeric(8, 2) NOT NULL,
    measurement_unit_id integer,
    hirarchy integer NOT NULL,
    PRIMARY KEY (id_ingredient)
);

CREATE TABLE IF NOT EXISTS flavourhaven.tool
(
    id_tool SERIAL NOT NULL,
    listing_id integer NOT NULL,
    name character varying(350) NOT NULL,
    hirarchy integer NOT NULL,
    PRIMARY KEY (id_tool)
);

CREATE TABLE IF NOT EXISTS flavourhaven.measurement_unit
(
    id_measurement_unit SERIAL NOT NULL,
    name character varying(35) NOT NULL,
    symbol character varying(5) NOT NULL,
    measurment_type_id integer NOT NULL,
    is_base_unit boolean NOT NULL,
    multiplication_ratio_to_base_unit double precision NOT NULL,
    addition_ratio_to_base_unit double precision NOT NULL,
    PRIMARY KEY (id_measurement_unit)
);

CREATE TABLE IF NOT EXISTS flavourhaven.measurement_type
(
    id_measurement_type SERIAL NOT NULL,
    name character varying(35) NOT NULL,
    PRIMARY KEY (id_measurement_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.step
(
    id_step SERIAL NOT NULL,
    listing_id integer NOT NULL,
    title character varying(100),
    text text NOT NULL,
    hirarchy numeric(8, 1) NOT NULL,
    PRIMARY KEY (id_step)
);



-- |--- content ---|
SAVEPOINT "content";

CREATE TABLE IF NOT EXISTS flavourhaven.content
(
    id_content SERIAL NOT NULL,
    recipe_id integer NOT NULL,
    text text NOT NULL,
    hirarchy integer NOT NULL,
    content_type_id integer NOT NULL,
    PRIMARY KEY (id_content)
);

CREATE TABLE IF NOT EXISTS flavourhaven.content_type
(
    id_content_type SERIAL NOT NULL,
    name integer NOT NULL,
    PRIMARY KEY (id_content_type)
);



-- |--- ban ---|
SAVEPOINT "ban";

CREATE TABLE IF NOT EXISTS flavourhaven.ban
(
    id_ban SERIAL NOT NULL,
    banned_account_id integer NOT NULL,
    banned_by_account_id integer NOT NULL,
    report_id integer NOT NULL,
    ban_created_on timestamp without time zone NOT NULL,
    ban_untile timestamp without time zone NOT NULL,
    reason_message text,
    is_forgiven boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id_ban)
);



-- |--- report ---|
SAVEPOINT "report";

CREATE TABLE IF NOT EXISTS flavourhaven.report
(
    id_report SERIAL NOT NULL,
    report_by_account_id integer NOT NULL,
    reason text NOT NULL,
    was_acted_upon boolean NOT NULL DEFAULT false,
    urgency numeric(1, 0),
    PRIMARY KEY (id_report)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_report
(
    report_id integer NOT NULL,
    recipe_id integer NOT NULL,
    PRIMARY KEY (report_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_has_report
(
    report_id integer NOT NULL,
    account_id integer NOT NULL,
    PRIMARY KEY (report_id, account_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_has_report
(
    report_id integer NOT NULL,
    comment_id integer NOT NULL,
    PRIMARY KEY (report_id, comment_id)
);


-- |--- comment ---|
SAVEPOINT "comment";

CREATE TABLE IF NOT EXISTS flavourhaven.comment
(
    id_comment SERIAL NOT NULL,
    text text NOT NULL,
    made_by_account_id integer NOT NULL,
    PRIMARY KEY (id_comment)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_on_comment
(
    comment_id integer NOT NULL,
    on_comment_id integer NOT NULL,
    PRIMARY KEY (on_comment_id, comment_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_on_recipe
(
    comment_id integer NOT NULL,
    on_recipe_id integer NOT NULL,
    PRIMARY KEY (comment_id, on_recipe_id)
);



-- |--- role and website right ---|
SAVEPOINT "role and website right";

CREATE TABLE IF NOT EXISTS flavourhaven.role
(
    id_role SERIAL NOT NULL,
    power_hirarchy integer NOT NULL,
    name character varying(35) NOT NULL,
    tag character varying(35),
    max_content integer,
    report_cooldown_in_min integer,
	PRIMARY KEY (id_role)
);

CREATE TABLE IF NOT EXISTS flavourhaven.website_right
(
    id_website_right SERIAL NOT NULL,
    "right" text NOT NULL,
    PRIMARY KEY (id_website_right)
);

CREATE TABLE IF NOT EXISTS flavourhaven.role_has_website_right
(
    id_role_has_website_right SERIAL NOT NULL,
    role_id integer NOT NULL,
    website_right_id integer NOT NULL,
    PRIMARY KEY (id_role_has_website_right)
);





-- |---------- adding foren keyes ----------|

-- |--- account ---|
SAVEPOINT "foren key account";

ALTER TABLE IF EXISTS flavourhaven.account
    ADD FOREIGN KEY (role_id)
    REFERENCES flavourhaven.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS flavourhaven.account_saves_recipe
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_saves_recipe
    ADD FOREIGN KEY (saved_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_recipe
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_recipe
    ADD FOREIGN KEY (rated_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_comment
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_comment
    ADD FOREIGN KEY (rated_comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_subscibes_account
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_subscibes_account
    ADD FOREIGN KEY (subscibed_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_blocks_account
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_blocks_account
    ADD FOREIGN KEY (blocked_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

    

-- |--- recipe ---|
SAVEPOINT "foren key recipe";

ALTER TABLE IF EXISTS flavourhaven.recipe
    ADD FOREIGN KEY (food_type_id)
    REFERENCES flavourhaven.account (id_food_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD FOREIGN KEY (reicipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD FOREIGN KEY (food_type_id)
    REFERENCES flavourhaven.food_type (id_food_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


    ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD FOREIGN KEY (reicipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD FOREIGN KEY (cuisine_id)
    REFERENCES flavourhaven.cuisine (id_cuisine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_account
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_account
    ADD FOREIGN KEY (links_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_recipe
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_recipe
    ADD FOREIGN KEY (links_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- mail ---|
SAVEPOINT "foren key mail";

ALTER TABLE IF EXISTS flavourhaven.mail
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- link ---|
SAVEPOINT "foren key link";

ALTER TABLE IF EXISTS flavourhaven.account_has_link
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_link
    ADD FOREIGN KEY (link_id)
    REFERENCES flavourhaven.link (id_link) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS flavourhaven.recipe_has_link
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

    ALTER TABLE IF EXISTS flavourhaven.recipe_has_link
    ADD FOREIGN KEY (link_id)
    REFERENCES flavourhaven.link (id_link) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- listing ---|
SAVEPOINT "foren key listing";

ALTER TABLE IF EXISTS flavourhaven.listing
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.listing
    ADD FOREIGN KEY (listing_type_id)
    REFERENCES flavourhaven.listing_type (id_listing_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ingredient
    ADD FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ingredient
    ADD FOREIGN KEY (measurement_unit_id)
    REFERENCES flavourhaven.measurement_unit (id_measurement_unit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS flavourhaven.measurement_unit
    ADD FOREIGN KEY (measurment_type_id)
    REFERENCES flavourhaven.measurement_type (id_measurement_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.tool
    ADD FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.step
    ADD FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- content ---|
SAVEPOINT "foren key content";

ALTER TABLE IF EXISTS flavourhaven.content
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.content
    ADD FOREIGN KEY (content_type_id)
    REFERENCES flavourhaven.content_type (id_content_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- ban ---|
SAVEPOINT "foren key ban";

ALTER TABLE IF EXISTS flavourhaven.ban
    ADD FOREIGN KEY (banned_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ban
    ADD FOREIGN KEY (banned_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ban
    ADD FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- report ---|
SAVEPOINT "foren key report";

ALTER TABLE IF EXISTS flavourhaven.report
    ADD FOREIGN KEY (report_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_report
    ADD FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_report
    ADD FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_report
    ADD FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_report
    ADD FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS flavourhaven.comment_has_report
    ADD FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_has_report
    ADD FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- comment ---|
SAVEPOINT "foren key comment";

ALTER TABLE IF EXISTS flavourhaven.comment
    ADD FOREIGN KEY (made_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_comment
    ADD FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_comment
    ADD FOREIGN KEY (on_comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_recipe
    ADD FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_recipe
    ADD FOREIGN KEY (on_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- |--- role and website right ---|
SAVEPOINT "foren key role and website right";

ALTER TABLE IF EXISTS flavourhaven.role_has_website_right
    ADD FOREIGN KEY (role_id)
    REFERENCES flavourhaven.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.role_has_website_right
    ADD FOREIGN KEY (website_right_id)
    REFERENCES flavourhaven.website_right (id_website_right) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMIT;

