-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at httpsgithub.compgadmin-orgpgadmin4issuesnewchoose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS flavourhaven.account
(
    id_account serial NOT NULL,
    user_name character varying(35) COLLATE pg_catalog.default NOT NULL,
    birth_date date NOT NULL,
    e-mail character varying(60) COLLATE pg_catalog.default NOT NULL,
    password character varying(60) COLLATE pg_catalog.default NOT NULL,
    created_on timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp without time zone,
    is_active boolean,
    role_id integer,
    last_pasword_reset timestamp without time zone,
    nickname character varying(35) COLLATE pg_catalog.default,
    profile_picture bytea,
    biography text COLLATE pg_catalog.default,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT account_pkey PRIMARY KEY (id_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_blocks_account
(
    id_account_blocks_account serial NOT NULL,
    account_id integer NOT NULL,
    blocked_account_id integer NOT NULL,
    CONSTRAINT account_blocks_account_pkey PRIMARY KEY (id_account_blocks_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_has_link
(
    id_account_has_link serial NOT NULL,
    link_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT account_has_link_pkey PRIMARY KEY (id_account_has_link)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_has_report
(
    report_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT account_has_report_pkey PRIMARY KEY (report_id, account_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_rates_comment
(
    id_account_rates_comment serial NOT NULL,
    account_id integer NOT NULL,
    rated_comment_id integer NOT NULL,
    is_positve boolean NOT NULL,
    CONSTRAINT account_rates_comment_pkey PRIMARY KEY (id_account_rates_comment)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_rates_recipe
(
    id_account_rates_recipe serial NOT NULL,
    account_id integer NOT NULL,
    rated_recipe_id integer NOT NULL,
    is_positive boolean NOT NULL,
    CONSTRAINT account_rates_recipe_pkey PRIMARY KEY (id_account_rates_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_saves_recipe
(
    id_account_saves_recipe serial NOT NULL,
    account_id integer NOT NULL,
    saved_recipe_id integer NOT NULL,
    CONSTRAINT account_saves_recipe_pkey PRIMARY KEY (id_account_saves_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_subscibes_account
(
    id_account_subscibes_account serial NOT NULL,
    account_id integer NOT NULL,
    subscibed_account_id integer NOT NULL,
    CONSTRAINT account_subscibes_account_pkey PRIMARY KEY (id_account_subscibes_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.account_views_recipe
(
    id_account_views_recipe serial NOT NULL,
    account_id integer NOT NULL,
    viewed_recipe_id integer NOT NULL,
    CONSTRAINT account_views_recipe_pkey PRIMARY KEY (id_account_views_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.ban
(
    id_ban serial NOT NULL,
    banned_account_id integer NOT NULL,
    banned_by_account_id integer NOT NULL,
    report_id integer NOT NULL,
    ban_created_on timestamp without time zone NOT NULL,
    ban_untile timestamp without time zone NOT NULL,
    reason_message text COLLATE pg_catalog.default,
    is_forgiven boolean NOT NULL DEFAULT false,
    CONSTRAINT ban_pkey PRIMARY KEY (id_ban)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment
(
    id_comment serial NOT NULL,
    text text COLLATE pg_catalog.default NOT NULL,
    made_by_account_id integer NOT NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (id_comment)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_has_report
(
    report_id integer NOT NULL,
    comment_id integer NOT NULL,
    CONSTRAINT comment_has_report_pkey PRIMARY KEY (report_id, comment_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_on_comment
(
    comment_id integer NOT NULL,
    on_comment_id integer NOT NULL,
    CONSTRAINT comment_on_comment_pkey PRIMARY KEY (on_comment_id, comment_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.comment_on_recipe
(
    comment_id integer NOT NULL,
    on_recipe_id integer NOT NULL,
    CONSTRAINT comment_on_recipe_pkey PRIMARY KEY (comment_id, on_recipe_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.content
(
    id_content serial NOT NULL,
    recipe_id integer NOT NULL,
    text text COLLATE pg_catalog.default NOT NULL,
    hirarchy integer NOT NULL,
    content_type_id integer NOT NULL,
    CONSTRAINT content_pkey PRIMARY KEY (id_content)
);

CREATE TABLE IF NOT EXISTS flavourhaven.content_type
(
    id_content_type serial NOT NULL,
    name character varying(15) COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT content_type_pkey PRIMARY KEY (id_content_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.cuisine
(
    id_cuisine serial NOT NULL,
    name character varying(50) COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT cuisine_pkey PRIMARY KEY (id_cuisine)
);

CREATE TABLE IF NOT EXISTS flavourhaven.food_type
(
    id_food_type serial NOT NULL,
    name character varying(30) COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT food_type_pkey PRIMARY KEY (id_food_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.ingredient
(
    id_ingredient serial NOT NULL,
    listing_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog.default NOT NULL,
    additional_information text COLLATE pg_catalog.default NOT NULL,
    hirarchy integer NOT NULL,
    amount_in_metric numeric(8, 2),
    amount_in_uscs numeric(8, 2),
    metric_mass_unit character varying(30) COLLATE pg_catalog.default,
    uscs_mass_unit character varying(30) COLLATE pg_catalog.default,
    CONSTRAINT ingredient_pkey PRIMARY KEY (id_ingredient)
);

CREATE TABLE IF NOT EXISTS flavourhaven.link
(
    id_link serial NOT NULL,
    link text COLLATE pg_catalog.default NOT NULL,
    where_to character varying(45) COLLATE pg_catalog.default NOT NULL,
    icon bytea,
    CONSTRAINT link_pkey PRIMARY KEY (id_link)
);

CREATE TABLE IF NOT EXISTS flavourhaven.listing
(
    id_listing serial NOT NULL,
    recipe_id integer NOT NULL,
    title character varying(50) COLLATE pg_catalog.default,
    hirarchy integer NOT NULL,
    listing_type_id integer NOT NULL,
    CONSTRAINT listing_pkey PRIMARY KEY (id_listing)
);

CREATE TABLE IF NOT EXISTS flavourhaven.listing_type
(
    id_listing_type serial NOT NULL,
    name character varying(15) COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT listing_type_pkey PRIMARY KEY (id_listing_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.mail
(
    id_mail serial NOT NULL,
    account_id integer NOT NULL,
    text text COLLATE pg_catalog.default,
    was_seen boolean DEFAULT false,
    CONSTRAINT mail_pkey PRIMARY KEY (id_mail)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe
(
    id_recipe serial NOT NULL,
    title character varying(60) COLLATE pg_catalog.default NOT NULL,
    thumbnail bytea NOT NULL,
    main_image bytea,
    cooking_video bytea,
    resting_time_in_min integer,
    preparation_time_in_min integer,
    cooking_time_in_min integer,
    serving_amount numeric(4, 2),
    creator_account_id integer NOT NULL,
    when_sesonality character varying(60) COLLATE pg_catalog.default,
    is_deleted boolean NOT NULL DEFAULT false,
    is_public boolean DEFAULT false,
    CONSTRAINT recipe_pkey PRIMARY KEY (id_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_cuisine
(
    id_recipe_has_cuisine serial NOT NULL,
    recipe_id integer NOT NULL,
    cuisine_id integer NOT NULL,
    CONSTRAINT recipe_has_cuisine_pkey PRIMARY KEY (id_recipe_has_cuisine)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_food_type
(
    id_recipe_has_food_type serial NOT NULL,
    recipe_id integer NOT NULL,
    food_type_id integer NOT NULL,
    CONSTRAINT recipe_has_food_type_pkey PRIMARY KEY (id_recipe_has_food_type)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_link
(
    id_recipe_has_link serial NOT NULL,
    link_id integer NOT NULL,
    recipe_id integer NOT NULL,
    CONSTRAINT recipe_has_link_pkey PRIMARY KEY (id_recipe_has_link)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_has_report
(
    report_id integer NOT NULL,
    recipe_id integer NOT NULL,
    CONSTRAINT recipe_has_report_pkey PRIMARY KEY (report_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_links_account
(
    id_recipe_links_account serial NOT NULL,
    recipe_id integer NOT NULL,
    links_account_id integer NOT NULL,
    description character varying(100) COLLATE pg_catalog.default,
    CONSTRAINT recipe_links_account_pkey PRIMARY KEY (id_recipe_links_account)
);

CREATE TABLE IF NOT EXISTS flavourhaven.recipe_links_recipe
(
    id_recipe_links_recipe serial NOT NULL,
    recipe_id integer NOT NULL,
    links_recipe_id integer NOT NULL,
    description character varying(100) COLLATE pg_catalog.default,
    CONSTRAINT recipe_links_recipe_pkey PRIMARY KEY (id_recipe_links_recipe)
);

CREATE TABLE IF NOT EXISTS flavourhaven.report
(
    id_report serial NOT NULL,
    report_by_account_id integer NOT NULL,
    reason text COLLATE pg_catalog.default NOT NULL,
    was_acted_upon boolean NOT NULL DEFAULT false,
    urgency numeric(1, 0),
    CONSTRAINT report_pkey PRIMARY KEY (id_report)
);

CREATE TABLE IF NOT EXISTS flavourhaven.role
(
    id_role serial NOT NULL,
    power_hirarchy integer NOT NULL,
    name character varying(35) COLLATE pg_catalog.default NOT NULL,
    tag character varying(35) COLLATE pg_catalog.default,
    max_content integer,
    report_cooldown_in_min integer,
    CONSTRAINT role_pkey PRIMARY KEY (id_role)
);

CREATE TABLE IF NOT EXISTS flavourhaven.role_has_website_right
(
    id_role_has_website_right serial NOT NULL,
    role_id integer NOT NULL,
    website_right_id integer NOT NULL,
    CONSTRAINT role_has_website_right_pkey PRIMARY KEY (id_role_has_website_right)
);

CREATE TABLE IF NOT EXISTS flavourhaven.step
(
    id_step serial NOT NULL,
    listing_id integer NOT NULL,
    title character varying(100) COLLATE pg_catalog.default,
    text text COLLATE pg_catalog.default NOT NULL,
    hirarchy numeric(8, 1) NOT NULL,
    CONSTRAINT step_pkey PRIMARY KEY (id_step)
);

CREATE TABLE IF NOT EXISTS flavourhaven.tool
(
    id_tool serial NOT NULL,
    listing_id integer NOT NULL,
    name character varying(350) COLLATE pg_catalog.default NOT NULL,
    hirarchy integer NOT NULL,
    CONSTRAINT tool_pkey PRIMARY KEY (id_tool)
);

CREATE TABLE IF NOT EXISTS flavourhaven.website_right
(
    id_website_right serial NOT NULL,
    rights text COLLATE pg_catalog.default NOT NULL,
    CONSTRAINT website_right_pkey PRIMARY KEY (id_website_right)
);

ALTER TABLE IF EXISTS flavourhaven.account
    ADD CONSTRAINT account_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES flavourhaven.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_blocks_account
    ADD CONSTRAINT account_blocks_account_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_blocks_account
    ADD CONSTRAINT account_blocks_account_blocked_account_id_fkey FOREIGN KEY (blocked_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_link
    ADD CONSTRAINT account_has_link_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_link
    ADD CONSTRAINT account_has_link_link_id_fkey FOREIGN KEY (link_id)
    REFERENCES flavourhaven.link (id_link) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_report
    ADD CONSTRAINT account_has_report_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_has_report
    ADD CONSTRAINT account_has_report_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_comment
    ADD CONSTRAINT account_rates_comment_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_comment
    ADD CONSTRAINT account_rates_comment_rated_comment_id_fkey FOREIGN KEY (rated_comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_recipe
    ADD CONSTRAINT account_rates_recipe_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_rates_recipe
    ADD CONSTRAINT account_rates_recipe_rated_recipe_id_fkey FOREIGN KEY (rated_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_saves_recipe
    ADD CONSTRAINT account_saves_recipe_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_saves_recipe
    ADD CONSTRAINT account_saves_recipe_saved_recipe_id_fkey FOREIGN KEY (saved_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_subscibes_account
    ADD CONSTRAINT account_subscibes_account_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_subscibes_account
    ADD CONSTRAINT account_subscibes_account_subscibed_account_id_fkey FOREIGN KEY (subscibed_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_views_recipe
    ADD CONSTRAINT account_views_recipe_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.account_views_recipe
    ADD CONSTRAINT account_views_recipe_viewed_recipe_id_fkey FOREIGN KEY (viewed_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ban
    ADD CONSTRAINT ban_banned_account_id_fkey FOREIGN KEY (banned_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ban
    ADD CONSTRAINT ban_banned_by_account_id_fkey FOREIGN KEY (banned_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ban
    ADD CONSTRAINT ban_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment
    ADD CONSTRAINT comment_made_by_account_id_fkey FOREIGN KEY (made_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_has_report
    ADD CONSTRAINT comment_has_report_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_has_report
    ADD CONSTRAINT comment_has_report_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_comment
    ADD CONSTRAINT comment_on_comment_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_comment
    ADD CONSTRAINT comment_on_comment_on_comment_id_fkey FOREIGN KEY (on_comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_recipe
    ADD CONSTRAINT comment_on_recipe_comment_id_fkey FOREIGN KEY (comment_id)
    REFERENCES flavourhaven.comment (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.comment_on_recipe
    ADD CONSTRAINT comment_on_recipe_on_recipe_id_fkey FOREIGN KEY (on_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.content
    ADD CONSTRAINT content_content_type_id_fkey FOREIGN KEY (content_type_id)
    REFERENCES flavourhaven.content_type (id_content_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.content
    ADD CONSTRAINT content_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.ingredient
    ADD CONSTRAINT ingredient_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.listing
    ADD CONSTRAINT listing_listing_type_id_fkey FOREIGN KEY (listing_type_id)
    REFERENCES flavourhaven.listing_type (id_listing_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.listing
    ADD CONSTRAINT listing_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.mail
    ADD CONSTRAINT mail_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe
    ADD CONSTRAINT recipe_creator_account_id_fkey FOREIGN KEY (creator_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_cuisine
    ADD CONSTRAINT recipe_has_cuisine_cuisine_id_fkey FOREIGN KEY (cuisine_id)
    REFERENCES flavourhaven.cuisine (id_cuisine) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_cuisine
    ADD CONSTRAINT recipe_has_cuisine_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD CONSTRAINT recipe_has_food_type_food_type_id_fkey FOREIGN KEY (food_type_id)
    REFERENCES flavourhaven.food_type (id_food_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_food_type
    ADD CONSTRAINT recipe_has_food_type_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_link
    ADD CONSTRAINT recipe_has_link_link_id_fkey FOREIGN KEY (link_id)
    REFERENCES flavourhaven.link (id_link) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_link
    ADD CONSTRAINT recipe_has_link_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_report
    ADD CONSTRAINT recipe_has_report_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_has_report
    ADD CONSTRAINT recipe_has_report_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES flavourhaven.report (id_report) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_account
    ADD CONSTRAINT recipe_links_account_links_account_id_fkey FOREIGN KEY (links_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_account
    ADD CONSTRAINT recipe_links_account_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_recipe
    ADD CONSTRAINT recipe_links_recipe_links_recipe_id_fkey FOREIGN KEY (links_recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.recipe_links_recipe
    ADD CONSTRAINT recipe_links_recipe_recipe_id_fkey FOREIGN KEY (recipe_id)
    REFERENCES flavourhaven.recipe (id_recipe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.report
    ADD CONSTRAINT report_report_by_account_id_fkey FOREIGN KEY (report_by_account_id)
    REFERENCES flavourhaven.account (id_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.role_has_website_right
    ADD CONSTRAINT role_has_website_right_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES flavourhaven.role (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.role_has_website_right
    ADD CONSTRAINT role_has_website_right_website_right_id_fkey FOREIGN KEY (website_right_id)
    REFERENCES flavourhaven.website_right (id_website_right) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.step
    ADD CONSTRAINT step_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS flavourhaven.tool
    ADD CONSTRAINT tool_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES flavourhaven.listing (id_listing) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;